Repository philip-soft/cupertino_calendar_picker, pull requests merged in 2025-02, with the labels that each got.

#32 v2.1.6
  CHANGELOG.md
  README.md
  lib/src/calendar/button/cupertino_calendar_picker_button.dart
  lib/src/time/button/cupertino_time_picker_button.dart
  pubspec.yaml
Labels: new version

#35 v2.1.7
  CHANGELOG.md
  README.md
  lib/src/calendar/button/cupertino_calendar_picker_button.dart
  lib/src/calendar/cupertino_calendar.dart
  lib/src/calendar/month_picker/calendar_month_picker.dart
  lib/src/calendar/overlay/cupertino_calendar_overlay.dart
  lib/src/calendar/picker/cupertino_calendar_picker.dart
  lib/src/calendar/weekdays/calendar_weekdays.dart
  lib/src/functions.dart
  lib/src/utils/package_date_utils.dart
  pubspec.yaml
Labels: new version, improvement

#36 v2.2.0
  CHANGELOG.md
  README.md
  doc/cupertino_calendar_picker_with_actions_dark.png
  doc/cupertino_calendar_picker_with_actions_light.png
  example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  example/lib/main.dart
  lib/cupertino_calendar_picker.dart
  lib/src/animations/calendar_animations.dart
  lib/src/calendar/actions/actions.dart
  lib/src/calendar/actions/calendar_action_decoration.dart
  lib/src/calendar/actions/calendar_actions.dart
  lib/src/calendar/actions/cupertino_calendar_action.dart
  lib/src/calendar/actions/cupertino_calendar_action_widget.dart
  lib/src/calendar/button/cupertino_calendar_picker_button.dart
  lib/src/calendar/calendar.dart
  lib/src/calendar/cupertino_calendar.dart
  lib/src/calendar/footer/calendar_footer_decoration.dart
  lib/src/calendar/overlay/cupertino_calendar_overlay.dart
  lib/src/calendar/picker/cupertino_calendar_picker.dart
  lib/src/config/package_config.dart
  lib/src/enums/calendar_dismiss_behavior.dart
  lib/src/functions.dart
  lib/src/picker/cupertino_picker_container.dart
  lib/src/picker/dividers/cupertino_picker_divider.dart
  lib/src/picker/dividers/cupertino_picker_vertical_divider.dart
  lib/src/picker/dividers/dividers.dart
  lib/src/picker/picker.dart
  pubspec.yaml
Labels: new version, improvement

#38 v2.2.1
  CHANGELOG.md
  README.md
  pubspec.yaml
Labels: new version

#40 Update cupertino_picker_button.dart
  lib/src/picker/button/cupertino_picker_button.dart
Labels: bug

#41 v2.2.2
  CHANGELOG.md
  README.md
  lib/src/picker/button/cupertino_picker_button.dart
  pubspec.yaml
Labels: new version
